#!/usr/bin/env bash
# cargo-init.sh — bootstrap a new Rust project with the course's defaults.
#
# Usage:  ./cargo-init.sh <project-name> [--lib]
#
# What it creates beyond `cargo new`:
#   - rust-toolchain.toml pinned to stable + clippy + rustfmt
#   - Cargo.toml with a tuned [profile.release]
#   - .clippy.toml that denies common footguns
#   - rustfmt.toml with sensible defaults
#   - .gitignore that covers /target, *.profraw, and editor scratch

set -euo pipefail

name="${1:-}"
flag="${2:-}"
if [[ -z "$name" ]]; then
  echo "usage: $0 <project-name> [--lib]" >&2
  exit 1
fi

if [[ "$flag" == "--lib" ]]; then
  cargo new --lib "$name"
else
  cargo new --bin "$name"
fi

cd "$name"

cat > rust-toolchain.toml <<'EOF'
[toolchain]
channel = "stable"
components = ["clippy", "rustfmt", "rust-analyzer"]
profile = "minimal"
EOF

# Replace the autogenerated Cargo.toml with a tuned version.
PKG_NAME="$name"
cat > Cargo.toml <<EOF
[package]
name = "$PKG_NAME"
version = "0.1.0"
edition = "2021"

[dependencies]

[dev-dependencies]

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
panic = "abort"
strip = "symbols"

[profile.bench]
inherits = "release"
debug = true

[profile.dev]
opt-level = 0
debug = true
overflow-checks = true
EOF

cat > rustfmt.toml <<'EOF'
edition = "2021"
max_width = 100
use_field_init_shorthand = true
use_try_shorthand = true
EOF

cat > clippy.toml <<'EOF'
msrv = "1.78.0"
EOF

# Append to .gitignore (cargo new already creates one)
cat >> .gitignore <<'EOF'
*.profraw
*.log
.vscode/
.idea/
EOF

echo "✓ Created Rust project '$name' with course defaults."
echo "   cd $name && cargo build && cargo clippy"
